name: Deploy to Production

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/productions/services/reality
            git pull
            tmux select-window -t main-production:1
            tmux send-keys -t main-production:1 C-c
            sleep 2
            tmux send-keys -t main-production:1 'make prod' Enter
